extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_ground_lights;
extern Lights1 bob_dl_wallground_lights;
extern Lights1 bob_dl_f3dlite_material_lights;
extern u8 bob_dl___ci8[];
extern u8 bob_dl___ci8_pal_rgba16[];
extern u8 bob_dl__2_ci8[];
extern u8 bob_dl__2_ci8_pal_rgba16[];
extern Vtx bob_dl_ground_mesh_layer_1_vtx_0[307];
extern Gfx bob_dl_ground_mesh_layer_1_tri_0[];
extern Vtx bob_dl_ground_mesh_layer_1_vtx_1[153];
extern Gfx bob_dl_ground_mesh_layer_1_tri_1[];
extern Vtx bob_dl_ground_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_ground_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_ground[];
extern Gfx mat_revert_bob_dl_ground[];
extern Gfx mat_bob_dl_wallground[];
extern Gfx mat_revert_bob_dl_wallground[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx bob_dl_ground_mesh_layer_1[];
extern Gfx bob_dl_ground_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
